---
kind: pipeline
type: docker
name: Build-Pipeline

steps:
- name: build-smwarm-pilot-NPM-${DRONE_TAG}
  image: registry.integral-systems.ch/library/node-builder:22
  environment:
    NPM_TOKEN:
      from_secret: npm-token
  commands:
  - npm install
  - npm version ${DRONE_TAG}
  - npm set //registry.npmjs.org/:_authToken=$${NPM_TOKEN}
  - npm build
  - npm publish --access public
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: origin
    commit: true
    commit_message: updated version to - ${DRONE_TAG}
    branch: master
  when:
    status:
    - success
    ref:
      include:
      - refs/tags/*
- name: Build-Container-swarm-pilot-${DRONE_TAG}
  image: plugins/docker
  settings:
    mtu: 1450
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.integral-systems.ch/integral-systems/swarm-pilot
    registry: registry.integral-systems.ch
    tags: ${DRONE_TAG}, latest
  when:
    ref:
      include:
      - refs/tags/*
- name: Push-docker-${DRONE_TAG}
  image: plugins/docker
  settings:
    mtu: 1450
    username:
      from_secret: docker-hub-username
    password:
      from_secret: docker-hub-password
    repo: gradlon/swarm-pilot
    purge: true
    tags:
      - ${DRONE_TAG}
      - latest
  when:
    ref:
      include:
      - refs/tags/*
- name: Notify-via-Telegram
  image: appleboy/drone-telegram
  settings:
    mtu: 1450
    token:
      from_secret: telegram_token
    to: 
      from_secret: telegram_default_groupe_id
    message_file: .drone/telegram_prod_build.tpl
  when:
    status:
    - failure
    - success
    ref:
      include:
      - refs/tags/*
trigger:
  event:
  - tag
############Production Deploy only##########
---
kind: pipeline
type: docker
name: Deploy-Production

steps:
- name: Deploy-Container-${DRONE_TAG}
  image: curlimages/curl
  environment:
    DEPLOY_URL:
      from_secret: deploy_url
  settings:
    mtu: 1450
  commands:
  - curl --max-time 240 --show-error --fail -X POST $${DEPLOY_URL}?SERVICE_TAG=${DRONE_TAG}
#############Notification###################
- name: Notify-via-Telegram
  image: appleboy/drone-telegram
  settings:
    mtu: 1450
    token:
      from_secret: telegram_token
    to: 
      from_secret: telegram_default_groupe_id
    message_file: .drone/telegram_prod_deploy.tpl
  when:
    status:
    - failure
    - success
- name: Notify-via-Mail
  image: drillster/drone-email
  settings:
    mtu: 1450
    host: smtp.gmail.com
    username:
      from_secret: gmail_user
    password:
      from_secret: gmail_pass
    from: admin@integralschweiz.org
    #recipients: [ gradlon@me.com ]
    #recipients_only: true
    body: file:///drone/src/.drone/mail_prod_deploy.hbs
    when:
      status: [ changed, failure, success ]
  when:
    status:
    - failure
    - success
trigger:
  event:
  - promote
  target:
  - production